name = "Pretty Optimized"
author = "gabeh"
version = "1.1.0-beta2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c9bb594ec898e4d3af198fcf671b917c2bd137301174e8d8f84cb564fa70d28"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
