name = "Pretty Optimized"
author = "gabeh"
version = "1.1.0-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e79ababd43f25d3a2cc8c9fa2874904b22cbc2839f68325a271d303571855ac2"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
