name = "Pretty Optimized"
author = "gabeh"
version = "1.1.0-beta5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da50f15d3594fd1877ed4ea38123d84d17e88504305f8e0dc0fd24eef6e8ac12"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
